### PR TITLE
Preparing documentation updates

### PR DESCRIPTION
**Pull request by OrKoN**

### CODE REVIEW

**Comment by OrKoN** [comment]
@guybedford I have the following questions so far:
- what is the Init mode(gettings-started.md) and what is the difference between them?
- where do I find the latest registry API?
- are there topics which are completely new in 0.17 and that have to be documented? I guess most of the topics are documented in the beta guide but is there something that needs to be added to the docs? Should the guide be the part of the docs?

**Comment by OrKoN** [comment]
@guybedford what is the difference between `package.json configFiles folder` and `package.json configFiles folder`. By default they point to the same directory. But `package.json directories.baseURL` is just `.` and `package.json configFiles folder` is `./`

**Comment by guybedford** [comment]
> what is the Init mode(gettings-started.md) and what is the difference between them?

For the init to be completely flexible we need a full manual configuration of all options. But in most cases the "quick" options are recommended for new users. The Standard options gives a middle ground between configurability and full custom flexibility.

> where do I find the latest registry API?

The registry API doc page has been kept up-to-date on the 0.17 branch I believe, if you look at the commits, on 0.17's diff, those show the breaking registry API changes. (It's just these three commits - https://github.com/jspm/jspm-cli/commit/3040d7156dd2744a702af72cd80bc4a4e4eabd45, https://github.com/jspm/jspm-cli/commit/f160125e1e05c194aba8b631111fe85c28a7c888, https://github.com/jspm/jspm-cli/commit/8de4b49c39c7c85d42f380366b68cb70c2155568)

> are there topics which are completely new in 0.17 and that have to be documented? I guess most of the topics are documented in the beta guide but is there something that needs to be added to the docs? Should the guide be the part of the docs?

In 0.17 the big change is that npm packages are not rewritten when installed, but rather configuration is generated for them which is in `jspm_packages/npm/package@x.y.z.json`. The other thing is that these individual package configurations can be manually modified and all overrides are retained in the project package.json. Along with this configuration system comes the features like conditional maps between browser and node which gives us the ability to build separately for these environments. Peer dependencies, disabling defaultJSExtensions etc. The original list is at https://github.com/jspm/jspm-cli/pull/1099#issue-105095945.

> what is the difference between `package.json configFiles folder` and `package.json configFiles folder`. By default they point to the same directory. But `package.json directories.baseURL` is just `.` and `package.json configFiles folder` is `./`

Because there are multiple config files, instead of prompting to ask where each one is located, in the standard init we just ask what folder they are in. On full custom init it will ask each config file individually I think? So you can have a baseURL `www`, while a configFileFolder `www/js` and then `jspm.browser.js`, `jspm.dev.js` and `jspm.config.js` all get loaded from there without the standard init having to ask each one separately. It's just trying to simplify and reduce the configuration options asked. In the package.json they are still stored separately though.

Thanks for moving this forward. I'm just working on SystemJS 0.20 which I'd like to bundle with jspm 0.17 for the release candidate next month and then maybe a release before the end of the year would even be possible!

**Comment by OrKoN** [comment]
@guybedford I guess it would be good to document options for every init mode separately? or the quick mode options are enough?

**Comment by guybedford** [comment]
@OrKoN it's a good point - at the moment the documentation is partly reference documentation, but also partly tutorial. If we keep the 0.17 beta guide as the "tutorial", then the focus can be on making this documentation more "api reference". So we should cover the comprehensive options, perhaps with the quick options highlighted in bold or something? Just throwing out ideas though - will trust your judgement here.

**Comment by unional** [comment]
@OrKoN , how can I work with you on this?

> On full custom init it will ask each config file individually I think?

Yes, each file can be individually customized.

**Comment by OrKoN** [comment]
@unional I have given you the write permissions. Feel free to commit on the docs branch.

**Comment by unional** [comment]
@guybedford do you have any preference on how the markdown are formatted? It is kinda over the place right now. I typically use markdownlint. If you want to keep the current format, I'll disable linting for this project. 🌷

**Comment by guybedford** [comment]
@unional these decisions are between you and @OrKoN :)

**Comment by OrKoN** [comment]
@unional I think the best is to focus on the content. Formatting can be fixed/improved later.

**Pull request closed without merging**
